// Vietnamese wording for the app's own words, keyed by the English. Written for a Vietnamese student at a US
// college, not machine-translated: everyday Vietnamese that addresses the reader as "bạn", the words students
// actually use (CV, offer, tín chỉ, môn tiên quyết), and English kept where she'll meet it in English anyway
// (Google Calendar, Handshake, iPhone menu names shown next to the Vietnamese ones).
export const VI: Record<string, string> = {
  // Views and sections
  "Plan": "Kế hoạch",
  "Internships": "Thực tập",
  "Calendar": "Lịch",
  "Skills": "Kỹ năng",
  "Summary": "Tóm tắt",
  "Library": "Môn học",
  "Checks": "Kiểm tra",
  "Mine": "Của tôi",
  "Guide": "Hướng dẫn",
  "Sections": "Mục",
  "Page": "Trang",

  // Header and example banner
  "Search everything (⌘K)": "Tìm mọi thứ (⌘K)",
  "Install this app": "Cài app này",
  "Install": "Cài",
  "You're looking at **example data**. Nothing here is saved.": "Bạn đang xem **dữ liệu mẫu**. Không có gì được lưu.",
  "**Example data.** Nothing is saved.": "**Dữ liệu mẫu**, không lưu.",
  "Start my own": "Tạo kế hoạch riêng",
  "Example · not saved": "Dữ liệu mẫu · không lưu",
  "Saved in this browser": "Đã lưu trên trình duyệt này",
  "Couldn't save. Browser storage is full or blocked": "Không lưu được. Bộ nhớ trình duyệt đã đầy hoặc bị chặn",
  "Cleared the example. This plan is yours now.": "Đã xoá dữ liệu mẫu. Giờ đây là kế hoạch của bạn.",
  "Started your own plan. First, mark the GSU classes you've taken.": "Đã tạo kế hoạch của bạn. Trước tiên, hãy đánh dấu các môn đã học ở GSU.",

  // Application statuses
  "To apply": "Cần nộp",
  "Working on": "Đang chuẩn bị",
  "Applied": "Đã nộp",
  "Interview": "Phỏng vấn",
  "Offer": "Có offer",
  "Closed": "Đã đóng",

  // School years
  "Freshman": "Năm nhất",
  "Sophomore": "Năm hai",
  "Junior": "Năm ba",
  "Senior": "Năm tư",
  "Graduate student": "Cao học",

  // Lists and deadlines
  "{a} and {b}": "{a} và {b}",
  "{a}, and {b}": "{a} và {b}",
  "or": "hoặc",
  "Due {date}": "Hạn {date}",
  "Overdue · {date}": "Quá hạn · {date}",
  "Due today · {date}": "Hạn hôm nay · {date}",
  "Due in {n}d · {date}": "Còn {n} ngày · {date}",
  "Overdue: {name}": "Quá hạn: {name}",
  "Due soon: {name}": "Sắp hết hạn: {name}",
  "Internship": "Thực tập",

  // Plan: the class planner
  "Needs {list} first": "Cần học {list} trước",
  "Take with {list}": "Phải học cùng kỳ với {list}",
  "Needs {n} accounting major classes first (you'd have {have})": "Cần học trước {n} môn chuyên ngành kế toán (bạn mới có {have})",
  "Best in your final semester": "Nên học vào học kỳ cuối",
  "1 class is out of order": "1 môn bị xếp sai thứ tự",
  "{n} classes are out of order": "{n} môn bị xếp sai thứ tự",
  "Planned before a prerequisite is done.": "Được xếp trước khi học xong môn tiên quyết.",
  "1 class left to place": "Còn 1 môn chưa xếp",
  "{n} classes left to place": "Còn {n} môn chưa xếp",
  "Place them yourself, or let the planner fill them in.": "Bạn có thể tự xếp, hoặc để app xếp giúp.",
  "Set up your semesters to start.": "Tạo các học kỳ để bắt đầu.",
  "Every requirement is covered": "Đã đủ mọi yêu cầu",
  "Done or planned, in an order that works.": "Tất cả đã học hoặc đã xếp, đúng thứ tự.",
  "{term} (needs an 18-hour semester)": "{term} (cần một kỳ học 18 tín chỉ)",
  "Earliest possible finish": "Tốt nghiệp sớm nhất",
  "Set your graduation date under Skills to check it.": "Nhập thời gian tốt nghiệp ở mục Kỹ năng để kiểm tra.",
  "Earliest possible: {term}": "Sớm nhất: {term}",
  "Graduate by {term}": "Tốt nghiệp kịp {term}",
  "Reachable. Earliest possible: {term}.": "Kịp. Sớm nhất là {term}.",
  "Not reachable at these loads. Earliest possible: {term}.": "Không kịp với số tín chỉ mỗi kỳ như hiện tại. Sớm nhất là {term}.",
  "{done} done, {planned} planned, {open} not planned": "{done} đã học, {planned} đã xếp, {open} chưa xếp",
  "planned": "đã xếp",
  "Earliest you could graduate": "Học kỳ sớm nhất bạn có thể tốt nghiệp",
  "Earliest finish": "Tốt nghiệp sớm nhất",
  "All": "Tất cả",
  "To place": "Chưa xếp",
  "Electives": "Tự chọn",
  "Done": "Đã học",
  "Search classes…": "Tìm môn học…",
  "Search classes": "Tìm môn học",
  "Show": "Hiển thị",
  "Nothing matches.": "Không có môn nào khớp.",
  "{shown} of {total}": "{shown} / {total}",
  "+ adds to {term}": "+ thêm vào {term}",
  "Add to {term}": "Thêm vào {term}",
  "Add {code} to {term}": "Thêm {code} vào {term}",
  "Added {code} to {term}.": "Đã thêm {code} vào {term}.",
  "Classes that need this one first": "Số môn cần học môn này trước",
  "{n} hrs": "{n} tín chỉ",
  "unlocks {n}": "mở {n} môn",
  "needs 1 class first": "cần học 1 môn trước",
  "needs {n} classes first": "cần học {n} môn trước",
  "optional": "không bắt buộc",
  "Plan your semesters": "Lên kế hoạch các học kỳ",
  "Add every semester from now until graduation, then fill them with classes.": "Tạo các học kỳ từ bây giờ đến lúc tốt nghiệp, rồi xếp môn vào.",
  "Set up my semesters": "Tạo các học kỳ",
  "Add term": "Thêm học kỳ",
  "Add a term": "Thêm học kỳ",
  "Remove {code}": "Bỏ {code}",
  "{code} planned for {term}.": "Đã xếp {code} vào {term}.",
  "More than {n} hours is a very heavy load.": "Hơn {n} tín chỉ là rất nặng.",
  "{n} classes, {hrs} credit hours": "{n} môn, {hrs} tín chỉ",
  "Tap again to remove this term": "Bấm lần nữa để xoá học kỳ này",
  "Remove term": "Xoá học kỳ",
  "Confirm removing {term}": "Xác nhận xoá {term}",
  "Remove {term}": "Xoá {term}",
  "Drag a class here, or use + in the library": "Kéo môn vào đây, hoặc bấm + trong danh sách môn",
  "Empty": "Trống",
  "Can I graduate?": "Tốt nghiệp kịp không?",
  "Prerequisites in order": "Môn tiên quyết đúng thứ tự",
  "Capstone in the last semester": "Môn capstone ở học kỳ cuối",
  "BUSA 4980 and BUSA 4990 go last": "BUSA 4980 và BUSA 4990 học sau cùng",
  "No semester over 18 hours": "Không kỳ nào quá 18 tín chỉ",
  "{n} hours": "{n} tín chỉ",
  "Puts each class in the earliest semester its prerequisites allow, at up to 15 hours (6 in summer)": "Xếp mỗi môn vào học kỳ sớm nhất mà môn tiên quyết cho phép, tối đa 15 tín chỉ mỗi kỳ (6 tín chỉ kỳ hè)",
  "Fill in remaining classes": "Tự xếp các môn còn lại",
  "Based on the {catalog}. Confirm your plan with a Robinson advisor.": "Dựa theo {catalog}. Hãy xác nhận kế hoạch với cố vấn học tập ở Robinson.",
  "Added your semesters through {grad}.": "Đã tạo các học kỳ đến {grad}.",
  "Added your semesters through graduation.": "Đã tạo các học kỳ đến lúc tốt nghiệp.",
  "Couldn't fit {list}, even at 18 hours a semester. Add a term, or check the red notes.": "Không xếp được {list}, kể cả khi học 18 tín chỉ mỗi kỳ. Thêm một học kỳ, hoặc xem các ghi chú màu đỏ.",
  "Everything fits, but only with some 18-hour semesters. Another term would lighten the load.": "Xếp đủ hết, nhưng có vài kỳ phải học 18 tín chỉ. Thêm một học kỳ sẽ nhẹ hơn.",
  "Filled in your remaining required classes.": "Đã xếp xong các môn bắt buộc còn lại.",

  // A class's details
  "done": "đã học",
  "not planned": "chưa xếp",
  "Prerequisites": "Môn tiên quyết",
  "None beyond the college's upper-division rules.": "Không có, ngoài quy định chung của trường cho các môn năm trên.",
  "Taken with": "Học cùng kỳ với",
  "Builds skills": "Kỹ năng học được",
  "Plan {code}": "Xếp lịch {code}",
  "Not planned": "Chưa xếp",
  "Plan for…": "Xếp vào kỳ…",
  "Taken · undo": "Đã học · hoàn tác",
  "{code} marked as taken.": "Đã đánh dấu {code} là đã học.",
  "I've taken this": "Tôi đã học môn này",
  "Close": "Đóng",

  // Internships: the board
  "Internships view": "Chế độ xem thực tập",
  "Board": "Bảng",
  "Results": "Kết quả",
  "**{n}** saved": "**{n}** đã lưu",
  "**{n}** working on": "**{n}** đang chuẩn bị",
  "**{n}** due soon": "**{n}** sắp hết hạn",
  "Deadline reminders and calendar sync": "Nhắc hạn nộp và đồng bộ lịch",
  "Reminders": "Nhắc nhở",
  "Add": "Thêm",
  "Add a posting": "Thêm tin tuyển dụng",
  "No postings yet": "Chưa có tin nào",
  "Find internships on Handshake, LinkedIn, or firm careers pages, then add them here to track them.": "Tìm việc thực tập trên Handshake, LinkedIn hoặc trang tuyển dụng của các công ty, rồi thêm vào đây để theo dõi.",
  "Needs attention": "Cần chú ý",
  "Untitled": "Chưa có tên",
  "Untitled posting": "Tin chưa có tên",
  "Drag a card here": "Kéo thẻ vào đây",
  "Remove priority": "Bỏ ưu tiên",
  "Mark as priority": "Đánh dấu ưu tiên",
  "Marked as priority.": "Đã đánh dấu ưu tiên.",
  "Priority removed.": "Đã bỏ ưu tiên.",
  "No deadline": "Không có hạn",
  "Skills matched": "Kỹ năng khớp",
  "{name} moved to {status}.": "Đã chuyển {name} sang “{status}”.",
  "Posting": "Tin tuyển dụng",

  // A posting's details
  "Example": "Ví dụ",
  "Open posting": "Mở tin gốc",
  "Add to Google Calendar": "Thêm vào Google Calendar",
  "Status": "Tình trạng",
  "Edit": "Sửa",
  "Edit posting": "Sửa tin",
  "Confirm delete": "Xác nhận xoá",
  "Delete posting": "Xoá tin",
  "Tap again to delete": "Bấm lần nữa để xoá",
  "Delete": "Xoá",
  "Posting deleted.": "Đã xoá tin.",
  "You have": "Bạn đã có",
  "Studying": "Đang học",
  "Partly, from classes": "Có một phần, nhờ các môn đã học",
  "Missing": "Còn thiếu",
  "Open in the skill guide": "Mở trong hướng dẫn kỹ năng",
  "No skills from the accounting list turned up in this text.": "Không tìm thấy kỹ năng kế toán nào trong nội dung này.",
  "Edit the posting and paste its text to see which skills it asks for.": "Sửa tin và dán nội dung vào để xem tin cần những kỹ năng gì.",
  "Posting text": "Nội dung tin",
  "For your resume": "Cho CV của bạn",
  "Paste your resume bullets under Skills, and this shows which ones to lead with for this job.": "Dán các dòng trong CV vào mục Kỹ năng, app sẽ chỉ ra nên đưa dòng nào lên đầu cho công việc này.",
  "Add resume bullets": "Thêm các dòng CV",
  "Lead with these bullets": "Đưa các dòng này lên đầu",
  "Use this posting's words": "Dùng đúng từ trong tin",
  "Say **“{phrase}”** so resume filters catch it. This bullet already shows it:": "Hãy viết **“{phrase}”** để hệ thống lọc CV nhận ra. Dòng này đã thể hiện điều đó:",
  "You have these, but no bullet shows them": "Bạn có các kỹ năng này, nhưng chưa dòng nào trong CV thể hiện",
  "None of your bullets match what this posting asks for yet. Check the missing skills above.": "Chưa dòng nào trong CV khớp với yêu cầu của tin này. Xem các kỹ năng còn thiếu ở trên.",

  // Add or edit a posting
  "Paste the job description…": "Dán mô tả công việc vào đây…",
  "Paste the whole job description. That's what the skill check reads.": "Dán toàn bộ mô tả công việc. App dựa vào đó để kiểm tra kỹ năng.",
  "Company": "Công ty",
  "Role": "Vị trí",
  "Link": "Link",
  "Deadline": "Hạn nộp",
  "Cancel": "Huỷ",
  "Save changes": "Lưu thay đổi",
  "Add posting": "Thêm tin",
  "You already saved this posting: **{name}** ({status}). The same link can't be added twice.": "Bạn đã lưu tin này rồi: **{name}** ({status}). Không thể thêm cùng một link hai lần.",
  "Open the saved one": "Mở tin đã lưu",
  "The posting was long, so only the first {n} characters were kept.": "Tin quá dài nên chỉ giữ {n} ký tự đầu.",
  "Posting updated.": "Đã cập nhật tin.",
  "Posting added.": "Đã thêm tin.",

  // Results across postings
  "What your 1 posting asks for": "Tin của bạn cần những gì",
  "What your {n} postings ask for": "{n} tin của bạn cần những gì",
  "Add at least 5 postings for results you can rely on.": "Thêm ít nhất 5 tin để kết quả đáng tin cậy hơn.",
  "Average match": "Mức khớp trung bình",
  "of each posting's skills": "số kỹ năng của mỗi tin",
  "Skills asked for": "Kỹ năng được yêu cầu",
  "across all postings": "trong tất cả các tin",
  "of those skills": "trong số đó",
  "Study next": "Nên học tiếp",
  "The skills these postings ask for most that you don't have yet.": "Các kỹ năng được yêu cầu nhiều nhất mà bạn chưa có.",
  "Asked for in {count} of {n} postings ({pct}%).": "Có trong {count}/{n} tin ({pct}%).",
  "You're partly there from your classes.": "Bạn đã có một phần nhờ các môn đã học.",
  "Learn free": "Học miễn phí",
  "Start studying": "Bắt đầu học",
  "Most requested skills": "Kỹ năng được yêu cầu nhiều nhất",
  "Every skill these postings ask for, from most to least common. Tap one to learn about it.": "Tất cả kỹ năng mà các tin yêu cầu, từ phổ biến nhất trở xuống. Bấm vào để tìm hiểu.",
  "By type of internship": "Theo loại thực tập",
  "Different jobs look for different things. Sorted from the type you've saved most.": "Mỗi loại việc cần những thứ khác nhau. Xếp theo loại bạn lưu nhiều nhất.",
  "1 posting": "1 tin",
  "{n} postings": "{n} tin",
  "Where to find more postings": "Tìm thêm tin ở đâu",
  "**Handshake** (GSU's job board) and Robinson career fairs": "**Handshake** (trang việc làm của GSU) và các hội chợ việc làm của Robinson",
  "**Firm careers pages:** the Big 4, RSM, Grant Thornton, BDO, Crowe": "**Trang tuyển dụng của các công ty:** Big 4, RSM, Grant Thornton, BDO, Crowe",
  "**Atlanta CPA firms** through the Georgia Society of CPAs": "**Các công ty CPA ở Atlanta** qua Georgia Society of CPAs",
  "**GSU groups:** Beta Alpha Psi, Tau Alpha Chi, NABA, ALPFA, ASCEND": "**Các hội nhóm ở GSU:** Beta Alpha Psi, Tau Alpha Chi, NABA, ALPFA, ASCEND",
  "Many firms fill next summer's internships in the fall of junior year. Busy-season internships run about January to April.": "Nhiều công ty tuyển thực tập hè năm sau ngay từ mùa thu năm ba. Thực tập mùa cao điểm (busy season) thường kéo dài từ tháng 1 đến tháng 4.",

  // Skills
  "Have": "Đã có",
  "Partly": "Một phần",
  "Not yet": "Chưa có",
  "About you": "Về bạn",
  "Name": "Tên",
  "Year": "Năm học",
  "Graduation": "Tốt nghiệp",
  "My skills": "Kỹ năng của tôi",
  "Add a skill, then Enter": "Thêm kỹ năng rồi bấm Enter",
  "Or open any skill in the guide and tap “I have this.”": "Hoặc mở một kỹ năng trong phần hướng dẫn và bấm “Tôi có kỹ năng này”.",
  "Remove {name}": "Bỏ {name}",
  "Resume bullets": "Các dòng trong CV",
  "Paste the bullets from your resume, one per line. Each posting then shows which ones to lead with and what to reword.": "Dán các dòng (bullet) trong CV của bạn, mỗi dòng một ý, và giữ bằng tiếng Anh như trong CV. Mỗi tin tuyển dụng sẽ gợi ý nên đưa dòng nào lên đầu và nên sửa chữ nào.",
  "Classes": "Môn học",
  "1 GSU class marked as taken.": "Đã đánh dấu 1 môn ở GSU là đã học.",
  "{n} GSU classes marked as taken.": "Đã đánh dấu {n} môn ở GSU là đã học.",
  "Mark them in Plan": "Đánh dấu ở mục Kế hoạch",
  "Other classes": "Môn khác",
  "transfer or not listed": "chuyển tín chỉ hoặc không có trong danh sách",
  "Add a class, then Enter": "Thêm môn rồi bấm Enter",
  "Your data": "Dữ liệu của bạn",
  "Everything saves in this browser only. Back up now and then, and restore the file to move to another device.": "Mọi thứ chỉ lưu trên trình duyệt này. Thỉnh thoảng hãy sao lưu, và dùng file đó để khôi phục khi đổi sang máy khác.",
  "Back up": "Sao lưu",
  "Restore": "Khôi phục",
  "Skill guide": "Hướng dẫn kỹ năng",
  "What each skill means, how to check yourself, and free places to learn it. Keep only the skills you could talk about in an interview.": "Mỗi kỹ năng là gì, cách tự kiểm tra và nơi học miễn phí. Chỉ giữ những kỹ năng bạn tự tin nói về trong buổi phỏng vấn.",
  "Studying now": "Đang học",
  "Nothing yet": "Chưa có gì",
  "1 skill": "1 kỹ năng",
  "{n} skills": "{n} kỹ năng",
  "Tap one to see where to learn it.": "Bấm vào để xem học ở đâu.",
  "Open a skill and tap “I'm learning this.”": "Mở một kỹ năng và bấm “Tôi đang học”.",
  "What it is": "Kỹ năng này là gì",
  "You have it if": "Bạn có kỹ năng này nếu",
  "How to learn it": "Cách học",
  "Free places to start": "Học miễn phí ở đâu",
  "Counted because of {list}.": "Được tính nhờ {list}.",
  "I have this": "Tôi có kỹ năng này",
  "I don't have this yet": "Tôi chưa có kỹ năng này",
  "Added {skill} to your skills.": "Đã thêm {skill} vào kỹ năng của bạn.",
  "Removed {skill} from your skills.": "Đã bỏ {skill} khỏi kỹ năng của bạn.",
  "I'm learning this": "Tôi đang học",
  "Stop studying": "Bỏ khỏi Đang học",
  "Added {skill} to Studying now.": "Đã thêm {skill} vào mục Đang học.",
  "Took {skill} off Studying now.": "Đã bỏ {skill} khỏi mục Đang học.",
  "Your classes still count toward it.": "Các môn bạn đã học vẫn được tính.",

  // Calendar
  "Day": "Ngày",
  "Week": "Tuần",
  "Month": "Tháng",
  "View": "Chế độ xem",
  "Today": "Hôm nay",
  "Previous": "Trước",
  "Next": "Sau",
  "Previous month": "Tháng trước",
  "Next month": "Tháng sau",
  "Calendars": "Các lịch",
  "Application deadlines": "Hạn nộp đơn",
  "shown": "đang hiện",
  "not connected": "chưa kết nối",
  "Red is due within 3 days or overdue, amber within a week. Nothing from Google Calendar is saved in the app.": "Đỏ là còn dưới 3 ngày hoặc đã quá hạn, cam là còn dưới 1 tuần. App không lưu gì từ Google Calendar.",
  "all-day": "cả ngày",
  "{n} more": "thêm {n}",
  "Apply: {name}": "Nộp đơn: {name}",
  "Show Google Calendar": "Hiện Google Calendar",
  "Showing your Google Calendar for this visit.": "Đang hiện Google Calendar của bạn trong lần mở này.",
  "Connecting…": "Đang kết nối…",
  "Updated {time}. Refresh": "Cập nhật lúc {time}. Làm mới",
  "Refresh": "Làm mới",
  "Refresh Google Calendar": "Làm mới Google Calendar",
  "Couldn't load Google Calendar.": "Không tải được Google Calendar.",

  // Deadlines and reminders
  "Deadlines & reminders": "Hạn nộp & nhắc nhở",
  "Deadlines & reminders (calendar, alerts, install)": "Hạn nộp & nhắc nhở (lịch, thông báo, cài app)",
  "None of your saved postings has a deadline you still need to apply by.": "Không có tin nào còn hạn nộp phía trước.",
  "1 application deadline still ahead of you. Put it in your calendar so your phone reminds you.": "Bạn còn 1 hạn nộp sắp tới. Thêm vào lịch để điện thoại nhắc bạn.",
  "{n} application deadlines still ahead of you. Put them in your calendar so your phone reminds you.": "Bạn còn {n} hạn nộp sắp tới. Thêm vào lịch để điện thoại nhắc bạn.",
  "These are example postings. Click “Start my own” at the top and add your real postings, then sync them to Google Calendar.": "Đây là các tin mẫu. Bấm “Tạo kế hoạch riêng” ở trên cùng, thêm các tin thật của bạn, rồi đồng bộ với Google Calendar.",
  "Adds each deadline to your Google Calendar, with phone reminders at 9am three days before and the day before. Sync again after changes; it updates the same events instead of adding copies.": "Thêm từng hạn nộp vào Google Calendar, điện thoại sẽ nhắc lúc 9 giờ sáng, trước 3 ngày và trước 1 ngày. Khi có thay đổi, bấm đồng bộ lại: app cập nhật đúng các sự kiện cũ, không tạo bản trùng.",
  "Sync to Google Calendar": "Đồng bộ với Google Calendar",
  "Syncing…": "Đang đồng bộ…",
  "Google Calendar updated: {added} added, {updated} updated, {removed} removed.": "Đã cập nhật Google Calendar: thêm {added}, sửa {updated}, xoá {removed}.",
  "Google Calendar sync didn't finish.": "Đồng bộ Google Calendar chưa xong.",
  "Calendar file": "File lịch",
  "Works with Google, Apple, and Outlook calendars. Open the file, or import it at calendar.google.com under Settings → Import. Each posting also has its own “Add to Google Calendar” link.": "Dùng được với lịch Google, Apple và Outlook. Mở file, hoặc nhập vào calendar.google.com ở Settings → Import. Mỗi tin cũng có nút “Thêm vào Google Calendar” riêng.",
  "Download deadlines (.ics)": "Tải hạn nộp (.ics)",
  "Calendar file saved. Open it to add your deadlines.": "Đã lưu file lịch. Mở file để thêm các hạn nộp.",
  "Deadline alerts": "Thông báo hạn nộp",
  "On iPhone, alerts work after you add this app to your Home Screen: tap Share, then Add to Home Screen, and open it from there.": "Trên iPhone, thông báo chỉ hoạt động khi bạn thêm app ra màn hình chính: bấm Share (Chia sẻ), chọn Add to Home Screen (Thêm vào MH chính), rồi mở app từ đó.",
  "This browser doesn't support alerts. Calendar reminders still work.": "Trình duyệt này không hỗ trợ thông báo. Nhắc nhở qua lịch vẫn hoạt động.",
  "On. You'll get an alert when you open the app and a deadline is within three days or past due. For reminders while the app is closed, use your calendar.": "Đang bật. Khi mở app, bạn sẽ nhận thông báo nếu có hạn nộp trong 3 ngày tới hoặc đã quá hạn. Muốn được nhắc cả khi không mở app, hãy dùng lịch.",
  "Turn on alerts": "Bật thông báo",
  "Deadline alerts are on.": "Đã bật thông báo hạn nộp.",
  "Alerts are blocked. You can allow them in your browser's site settings.": "Thông báo đang bị chặn. Bạn có thể cho phép trong phần cài đặt trang web của trình duyệt.",
  "Alerts show when you open the app. Calendar reminders work even when it's closed.": "Thông báo hiện khi bạn mở app. Nhắc nhở qua lịch vẫn hoạt động khi app đóng.",
  "Install on your phone": "Cài lên điện thoại",
  "Install app": "Cài app",
  "Installed.": "Đã cài.",
  "In Safari, tap Share, then Add to Home Screen.": "Trong Safari, bấm Share (Chia sẻ), rồi chọn Add to Home Screen (Thêm vào MH chính).",
  "In Chrome, open the menu and choose Install app (or Add to Home screen).": "Trong Chrome, mở menu và chọn Install app (Cài đặt ứng dụng) hoặc Add to Home screen.",

  // Google sign-in
  "Couldn't reach Google. Check your connection.": "Không kết nối được với Google. Kiểm tra lại mạng.",
  "Google Calendar sync isn't set up for this site.": "Trang này chưa được cài đặt để đồng bộ Google Calendar.",
  "Couldn't load Google sign-in.": "Không tải được trang đăng nhập Google.",
  "Google sign-in didn't finish.": "Chưa đăng nhập Google xong.",
  "Google sign-in was closed.": "Cửa sổ đăng nhập Google đã bị đóng.",
  "Google sign-in was blocked. Allow pop-ups and try again.": "Đăng nhập Google bị chặn. Hãy cho phép cửa sổ bật lên (pop-up) rồi thử lại.",
  "Google Calendar said: {message}": "Google Calendar báo lỗi: {message}",

  // Summary
  "Accounting B.B.A. plan": "Kế hoạch học Accounting B.B.A.",
  "{name}'s Accounting B.B.A. plan": "Kế hoạch học Accounting B.B.A. của {name}",
  "graduating {grad}": "tốt nghiệp {grad}",
  "Copy for my advisor": "Sao chép gửi cố vấn",
  "Copy plan for my advisor": "Sao chép kế hoạch gửi cố vấn",
  "Copies the plan in English, for your advisor": "Sao chép kế hoạch bằng tiếng Anh để gửi cố vấn",
  "Copy your plan": "Sao chép kế hoạch",
  "Copy this text and paste it into an email to your advisor.": "Sao chép đoạn này và dán vào email gửi cố vấn học tập.",
  "Copied (in English). Paste it into an email to your advisor.": "Đã sao chép (bằng tiếng Anh). Dán vào email gửi cố vấn học tập nhé.",
  "Planned through": "Đã xếp đến",
  "Nothing planned yet": "Chưa xếp gì",
  "Earliest possible": "Sớm nhất có thể",
  "All required classes are done": "Đã học xong tất cả môn bắt buộc",
  "{term} (with an 18-hour semester)": "{term} (có một kỳ học 18 tín chỉ)",
  "More than 12 semesters out": "Hơn 12 học kỳ nữa",
  "Graduation goal": "Mục tiêu tốt nghiệp",
  "Not set": "Chưa đặt",
  "Requirements": "Yêu cầu",
  "Still to place": "Chưa xếp",
  "Done or planned": "Đã học hoặc đã xếp",
  "Semesters": "Các học kỳ",
  "{n} classes": "{n} môn",
  "Nothing planned": "Chưa xếp môn nào",
  "No semesters yet. Set them up in Plan.": "Chưa có học kỳ nào. Tạo ở mục Kế hoạch.",
  "Done or in progress": "Đã học hoặc đang học",
  "None marked yet": "Chưa đánh dấu môn nào",
  "None added yet": "Chưa thêm tin nào",
  "Skills to work on": "Kỹ năng cần trau dồi",
  "Add postings to see which skills they ask for": "Thêm tin để xem các kỹ năng được yêu cầu",
  "Nothing missing from your postings": "Bạn đã đủ các kỹ năng trong các tin",

  // Backup and search
  "Back up my data": "Sao lưu dữ liệu",
  "Restore from a backup": "Khôi phục từ bản sao lưu",
  "Backup saved. Check your Downloads folder.": "Đã lưu bản sao lưu. Xem trong thư mục Downloads.",
  "That file isn't a backup from this app.": "File này không phải bản sao lưu của app.",
  "Restore this backup?": "Khôi phục bản sao lưu này?",
  "{classes} classes, {terms} semesters, {postings} postings. This replaces everything in the app now.": "{classes} môn, {terms} học kỳ, {postings} tin tuyển dụng. Toàn bộ dữ liệu hiện tại trong app sẽ bị thay thế.",
  "Replace my data": "Thay dữ liệu của tôi",
  "Backup restored.": "Đã khôi phục.",
  "Action": "Thao tác",
  "Class": "Môn học",
  "Skill": "Kỹ năng",
  "Go to {view}": "Đi tới {view}",
  "Search classes, skills, postings, or actions…": "Tìm môn học, kỹ năng, tin tuyển dụng hoặc thao tác…",
  "Search everything": "Tìm mọi thứ",
  "No matches.": "Không tìm thấy.",
};
